
#define CNTLR_SUCCESS   (OF_SUCCESS)

#define CNTLR_GENERIC_ERROR_START    10
#define CNTLR_GENERIC_ERROR_END (CNTLR_GENERIC_ERROR_START+ 100)

#define CNTLR_DPRM_ERROR_START  (CNTLR_GENERIC_ERROR_END +1)
#define CNTLR_DPRM_ERROR_END    (CNTLR_DPRM_ERROR_START + 100)

#define CNTLR_DPIFACE_EROOR_START (CNTLR_DPRM_ERROR_END + 1)
#define CNTLR_DPIFACE_EROOR_END  (CNTLR_DPIFACE_EROOR_START+ 100)

#define CNTLR_OF_MSG_ERROR_START (CNTLR_DPIFACE_EROOR_END + 1)
#define CNTLR_OF_MSG_ERROR_END   (CNTLR_DPIFACE_EROOR_START + 100)

#define CNTLR_APP_EVENT_ERROR_START  (CNTLR_OF_MSG_ERROR_END +1)
#define CNTLR_APP_EVENT_ERROR_END    (CNTLR_OF_MSG_ERROR_END +10)

#define CNTLR_OF_MSG_UTILITIES_ERROR_START (CNTLR_APP_EVENT_ERROR_END + 1)
#define CNTLR_OF_MSG_UTILITIES_ERROR_END   (CNTLR_OF_MSG_UTILITIES_ERROR_START + 100)

#define PSP_SUCCESS	CNTLR_SUCCESS

#define PSP_FAILURE	(-1)

/* Generic errors*/

enum generic_errors{
CNTLR_MEM_ALLOC_ERROR      = CNTLR_GENERIC_ERROR_START,
CNTLR_SEND_MSG_TO_DP_ERROR = (CNTLR_GENERIC_ERROR_START +1),
CNTLR_CHN_CLOSED           = (CNTLR_GENERIC_ERROR_START +2) 
};

enum dprm_errors {
DPRM_INVALID_DATAPATH_HANDLE = CNTLR_DPRM_ERROR_START,
DPRM_INVALID_DOMAIN_HANDLE   = (CNTLR_DPRM_ERROR_START+1)
}; 
/** Messaing Errors*/
enum messaging_errors{
OF_MSG_BUF_SIZE_IS_IN_SUFFECIENT = CNTLR_OF_MSG_ERROR_START,
OF_REG_ASYNC_HOOK_INVALID_EVENT_TYPE = (CNTLR_OF_MSG_ERROR_START+1),
OF_REG_ASYNC_HOOK_INVALID_APP_PRIORITY = (CNTLR_OF_MSG_ERROR_START +2),
OF_REG_ASYNC_HOOK_INVALID_NULL_CALLBACK = (CNTLR_OF_MSG_ERROR_START +3),
OF_REG_ASYNC_HOOK_DUPLICATE_APP_PRIOIRTY = (CNTLR_OF_MSG_ERROR_START +4),
OF_REG_ASYNC_HOOK_INVALID_DOMAIN = (CNTLR_OF_MSG_ERROR_START +5),
OF_REG_ASYNC_HOOK_INVALID_TABLEID = (CNTLR_OF_MSG_ERROR_START +6),
OF_REG_ASYNC_HOOK_NULL_CALLBACK = (CNTLR_OF_MSG_ERROR_START + 7),

OF_REG_SYMMETRIC_HOOK_INVALID_EVENT_TYPE = (CNTLR_OF_MSG_ERROR_START + 8),
OF_REG_SYMMETRIC_HOOK_NULL_CALLBACK = (CNTLR_OF_MSG_ERROR_START + 9),
OF_REG_SYMMETRIC_HOOK_INVALID_DOMAIN  = (CNTLR_OF_MSG_ERROR_START + 10),


OFU_ADD_FLOW_ENTRY_TO_TABLE_SUCCESS   = (CNTLR_OF_MSG_ERROR_START + 11),

OFU_ADD_GROUP_ENTRY_SUCCESS   = (CNTLR_OF_MSG_ERROR_START + 12),
OFU_MODIFY_GROUP_ENTRY_SUCCESS   = (CNTLR_OF_MSG_ERROR_START + 13),
OFU_DELETE_GROUP_ENTRY_SUCCESS   = (CNTLR_OF_MSG_ERROR_START + 14),
OFU_INSERT_BUCKET_TO_GROUP_SUCCESS   = (CNTLR_OF_MSG_ERROR_START + 15),
OFU_REMOVE_BUCKET_FROM_GROUP_SUCCESS = (CNTLR_OF_MSG_ERROR_START + 16),
OFU_MODIFY_FLOW_ENTRY_TO_TABLE_SUCCESS   = (CNTLR_OF_MSG_ERROR_START + 17),
OFU_DELETE_FLOW_ENTRY_TO_TABLE_SUCCESS	 = (CNTLR_OF_MSG_ERROR_START + 18),
OFU_ADD_METER_ENTRY_SUCCESS   = (CNTLR_OF_MSG_ERROR_START + 19),
OFU_MODIFY_METER_ENTRY_SUCCESS   = (CNTLR_OF_MSG_ERROR_START + 20),
OFU_DELETE_METER_ENTRY_SUCCESS   = (CNTLR_OF_MSG_ERROR_START + 21),

};

/*TBD SUCCESS values move it different place*/
enum msg_utilities {
OFU_NO_ROOM_IN_BUFFER = CNTLR_OF_MSG_UTILITIES_ERROR_START,
OFU_SET_FIELD_SUCCESS = (CNTLR_OF_MSG_UTILITIES_ERROR_START +1),
OFU_INSTRUCTION_PUSH_SUCCESS = (CNTLR_OF_MSG_UTILITIES_ERROR_START +2),
OFU_ACTION_PUSH_SUCCESS = (CNTLR_OF_MSG_UTILITIES_ERROR_START +3),
OFU_UNSUPPORTED_MATCH_FIELDS_TYPE_PASSED = (CNTLR_OF_MSG_UTILITIES_ERROR_START +4),
OFU_IN_PORT_FIELD_PRESENT = (CNTLR_OF_MSG_UTILITIES_ERROR_START +5),
OFU_IN_META_DATA_PRESENT = (CNTLR_OF_MSG_UTILITIES_ERROR_START +6),
OFU_IN_PORT_FIELD_NOT_PRESENT = (CNTLR_OF_MSG_UTILITIES_ERROR_START +7),
OFU_IN_META_DATA_NOT_PRESENT = (CNTLR_OF_MSG_UTILITIES_ERROR_START +8),
OFU_APPEND_BUCKET_SUCCESS=(CNTLR_OF_MSG_UTILITIES_ERROR_START +9),
OFU_APPEND_BAND_SUCCESS=(CNTLR_OF_MSG_UTILITIES_ERROR_START +10)
};

enum app_events {
CNTLR_REG_APP_INVALID_APP_EVENT_TYPE = CNTLR_APP_EVENT_ERROR_START,
CNTLR_REG_APP_EVENT_HOOK_INVALID_PRIORITY = (CNTLR_APP_EVENT_ERROR_START +1),
OF_REG_APP_EVNT_HOOK_INVALID_DOMAIN = (CNTLR_APP_EVENT_ERROR_START +2),
OF_REG_APP_EVNT_HOOK_DUPLICATE_APP_PRIOIRTY = (CNTLR_APP_EVENT_ERROR_START +3),
CNTLR_REG_APP_EVENT_HOOK_NULL_CALLBACK = (CNTLR_APP_EVENT_ERROR_START +4)};
