#ifndef __IPV4_FWD_TTP_H__
#define __IPV4_FWD_TTP_H__

#define IPV4_FWD_TTP_IN_PORT_CLASSIFY_TABLE_ID	(0)
#define IPV4_FWD_TTP_ETH_FILTERING_TABLE_ID	(1)
#define IPV4_FWD_TTP_ETH_CLASSIFY_TABLE_ID	(2)
#define IPV4_FWD_TTP_ARP_INBOUND_TABLE_ID	(3)
#define IPV4_FWD_TTP_IPV4_CLASSIFY_TABLE_ID	(4)
#define IPV4_FWD_TTP_IPV4_PBR_TABLE_ID		(5)
#define IPV4_FWD_TTP_IPV4_ROUTING_TABLE_ID	(6)
#define IPV4_FWD_TTP_IPV4_MCAST_GROUP_TABLE_ID  (7)
#define IPV4_FWD_TTP_IPV4_MCAST_ROUTING_TABLE_ID (8)

#define IPSEC_APP_SELF_CLASSIFICATION_TABLE_ID   9
#define IPSEC_APP_PACKET_CLASSIFICATION_TABLE_ID 10
#define IPSEC_APP_UDP_ENCAP_NATT_TABLE_ID        11
#define IPSEC_APP_IN_SA_TABLE_ID                 12
#define IPSEC_APP_IN_POLICY_TABLE_ID             13
#define IPSEC_APP_OUT_POLICY_TABLE_ID            14
#define IPSEC_APP_OUT_SA_TABLE_ID                15
#define IPV4_FWD_TTP_ARP_RESOLUTION_TABLE_ID	 16

#define IPV4_FWD_APP_PKT_IN_PRIORITY     (2)


#endif /* __IPV4_FWD_TTP_H__ */
