/* 
 *
 * Copyright  2012, 2013  Freescale Semiconductor
 *
 *
 * Licensed under the Apache License, version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
*/

/*
 *
 * File name: cbkerr.h
 * Author: G Atmaram <B38856@freescale.com>
 * Date:   03/25/2013
 * Description: 
 * 
 */

/* * * * * * * *  E R R O R S * * * * * * * * * * */
#define CM_SECAPPGLU_ERROR_BASE 10000
#define CM_SECAPPGLU_ERROR_STRING_LENGTH 256

#define ERROR_RESERVED "Error"

int32_t UCMAppGluGetErrMsg (int32_t err_index_i, char * err_arr_p);

typedef enum
{
  /* Generic error messages */ 
  CM_GLU_INVALID_IP_RANGE = CM_SECAPPGLU_ERROR_BASE,  
  CM_GLU_INVALID_PORT_RANGE,
  CM_GLU_IP_START_RANGE_GRT_END_RANGE,
  CM_GLU_PORT_START_RANGE_GRT_END_RANGE,
  CM_GLU_INVALID_IP_ADDR,  
  CM_GLU_INVALID_PORT,
  CM_GLU_INVALID_SUBMASK_ADDR,
  CM_GLU_INVALID_DOMAIN_NAME, 
  CM_GLU_MEM_ALLOC_FAIL,
  CM_GLU_INPUT_NULL,
  CM_GLU_NO_SUCH_RECORD,
  CM_GLU_INVALID_START_PORT,
  CM_GLU_INVALID_END_PORT, /* 10012*/

 /* Snet related error messages */
  CM_GLU_INVALID_SNET_NAME , /* 10013 */
  CM_GLU_SNET_DOESNT_EXIST, 
  CM_GLU_ADD_SNET_FAIL,


   /* IPDB related error messages */  
  CM_GLU_DUP_IPDB_REC, /* 10014 */
  CM_GLU_INVALID_IPDB_REC,
  CM_GLU_INVALID_IPDB_NAME,
  CM_GLU_INVALID_REC_TYPE  ,     
  CM_GLU_BEGIN_IPDB_TXN_FAIL,
  CM_GLU_END_IPDB_TXN_FAIL,    
  CM_GLU_ADD_IPDB_FAIL, /* 10022*/
  CM_GLU_MODIFY_IPDB_FAIL,
  CM_GLU_DEL_IPDB_FAIL,
  CM_GLU_GET_IPDB_FAIL,

 /* Service DB related error messages */  
  CM_GLU_DUP_SRVDB_REC, /* 10026 */
  CM_GLU_INVALID_SRVDB_REC,
  CM_GLU_INVALID_SRVDB_NAME,
  CM_GLU_INVALID_PORT_TYPE  ,     
  CM_GLU_BEGIN_SRVDB_TXN_FAIL,
  CM_GLU_END_SRVDB_TXN_FAIL,    
  CM_GLU_ADD_SRVDB_FAIL, /* 10032*/
  CM_GLU_MODIFY_SRVDB_FAIL,
  CM_GLU_DEL_SRVDB_FAIL,
  CM_GLU_GET_SRVDB_FAIL,
  CM_AUTOSYNC_SET_STATUS_FAILED,

  /*  ACL related error messages */
  CM_GLU_DUP_ACL_REC , /* 10036 */
  CM_GLU_INVALID_ACL_REC,
  CM_GLU_RULE_ID_OUT_OF_RANGE,
  CM_GLU_INVALID_RULE_ID,
  CM_GLU_INVALID_SRC_IP_TYPE,
  CM_GLU_INVALID_DEST_IP_TYPE,
  CM_GLU_INVALID_SRC_IP_ADDR, /* 10042 */
  CM_GLU_INVALID_DEST_IP_ADDR,
  CM_GLU_INVALID_SRC_IP_NAME,
  CM_GLU_INVALID_DEST_IP_NAME,
  CM_GLU_INVALID_SRC_IP_RANGE,
  CM_GLU_INVALID_DEST_IP_RANGE,
  CM_GLU_INVALID_SRC_IP_SUBNET,
  CM_GLU_INVALID_SRC_IP_MASK,
  CM_GLU_INVALID_DEST_IP_SUBNET, 
  CM_GLU_INVALID_DEST_IP_MASK, 
  CM_GLU_INVALID_SRC_NET_TYPE,/* 10052 */
  CM_GLU_INVALID_DEST_NET_TYPE,	 
  CM_GLU_INVALID_INS_BEF_RULEID,
  CM_GLU_INVALID_INS_AFT_RULEID,
  CM_GLU_INVALID_INS_POS,
  CM_GLU_SRC_IP_START_RANGE_GRT_END_RANGE,
  CM_GLU_DEST_IP_START_RANGE_GRT_END_RANGE,   
  CM_GLU_SRC_PORT_START_RANGE_GRT_END_RANGE,
  CM_GLU_DEST_PORT_START_RANGE_GRT_END_RANGE,
  CM_GLU_INVALID_SRC_PORT_START_RANGE,
  CM_GLU_INVALID_SRC_PORT_END_RANGE, /* 10062 */
  CM_GLU_INVALID_DEST_PORT_START_RANGE,
  CM_GLU_INVALID_DEST_PORT_END_RANGE,
  CM_GLU_INVALID_SRC_PORT_RANGE,
  CM_GLU_INVALID_DEST_PORT_RANGE,
  CM_GLU_INVALID_PROTO_PORT_COMBI,
  CM_GLU_INVALID_PROTO_SERVREC_COMBI,

 /* Ethernet related error messages */
  CM_GLU_INVALID_IFACE_NAME, /* 10069 */
  CM_GLU_NO_STATUS_CHANGE_FOR_ALIAS_IFACE, 
  CM_GLU_NO_WAN_IFACE_CFG,  
  CM_GLU_INVALID_DEFRT_OPTION, /* 10072 */
  CM_GLU_NO_HARDWARE_ADDR,  

  /* VLAN related error messages */
	CM_GLU_VLAN_FAILED, /* 10074 */
  CM_GLU_ADD_VLAN_FAILED,
  CM_GLU_SET_VLAN_NAME_TYPE_FAILED,  
  CM_GLU_SET_VLAN_FLAG_FAILED,
  CM_GLU_INVALID_SNET_TYPE,
  CM_GLU_INVALID_DELETE_VLAN_NAME,
  CM_GLU_VLAN_PHYIFACE_NOT_MODIFIABLE,
  CM_GLU_VLAN_NETTYPE_NOT_MODIFIABLE,

  /* Timewidow related error messages */
  CM_GLU_INVALID_TIMEWIN_NAME,  /* 10082 */
  CM_GLU_DUP_TIMEWIN_REC,
  CM_GLU_INVALID_OPENING_DAY,
  CM_GLU_INVALID_CLOSING_DAY,
  CM_GLU_INVALID_OPENING_HOUR,
  CM_GLU_INVALID_CLOSING_HOUR,

  /* Alias related error messages */
  CM_GLU_INVALID_ALIAS_NAME, /* 10088 */
  CM_GLU_ADD_ALIAS_FAILED,
  CM_GLU_SET_ALIAS_FAILED,
  CM_GLU_DEL_ALIAS_FAILED,

  /* ARP related error messages */
  CM_GLU_UNKNOWN_HOST, /* 10092 */
  CM_GLU_INVALID_HWARE_ADDR, /*10093 */

  /* Proxy ARP related error messages */
  CM_GLU_INVALID_PROXY_ARP_RECORD_NAME, /* 10094 */
  CM_GLU_DUP_PROXY_ARP_REC,
  CM_GLU_INVALID_START_IPADDR,
  CM_GLU_INVALID_END_IPADDR,

	/* Association reservation */
  CM_GLU_INVALID_NET_TYPE, /* 10098 */
  CM_GLU_INVALID_IP_TYPE,
  CM_GLU_INVALID_ASSORESV_COUNT,

	 /* RateLimit error messages*/
	 CM_GLU_ADD_RL_FAILED, /* 10101 */
	 CM_GLU_MOD_RL_FAILED,
	 CM_GLU_RL_MODIFY_CONN_NOT_ALLOWED, /* 10103 */
	 CM_GLU_RL_MORE_PARAMS_REQUIRED_FOR_DEL,
	 CM_GLU_INVALID_LIMIT_TYPE, /* 10105*/


   /* PortTrigger related error messages*/
  CM_GLU_INVALID_PORT_TRIGGER_NAME,
  CM_GLU_INVALID_TRIGGER_PROTOCOL,
  CM_GLU_INVALID_TRIGGER_PORT_RANGE,

/* VSG Zones related error messages */
  CM_GLU_VSG_ZONE_NO_ZONE_ID, 
  CM_GLU_VSG_ZONE_INVALID_ZONE_NAME,
  CM_GLU_VSG_ZONE_DUPLICATE_ZONE_NAME,
  CM_GLU_VSG_ZONE_ZONE_NAME_CANT_MODIFY,
  CM_GLU_VSG_ZONE_MODIFY_FAILED,
  CM_GLU_VSG_ZONE_ASSOC_IFACE_FAILED,
  CM_GLU_VSG_ZONE_DEASSOC_IFACE_FAILED, 

/* SSL Cerificate Related error messages */
  CM_GLU_SSL_ERROR_NO_CA_CERT_FILE_NAME, 
  CM_GLU_SSL_ERROR_NO_SELF_CERT_FILE_NAME,
  CM_GLU_SSL_ERROR_NO_PRIV_KEY_FILE_NAME,

  /* Namespace error messages */
  CM_GLU_NAMESPACE_NAME_NULL,
  CM_GLU_NAMESPACE_ADD_FAILED,
  CM_GLU_NAMESPACE_DOESNOT_EXIST,
  CM_GLU_NAMESPACE_DELETE_FAILED,
  CM_GLU_NAMESPACE_UPDATE_FAILED,
  CM_GLU_NAMESPACE_NAME_EXCEEDED,

  /* Datapath error messages */
  CM_GLU_DOMAIN_NAME_NULL, 
  CM_GLU_DATAPATH_ID_NULL, 
  CM_GLU_DATAPATH_ID_INVALID, 
  CM_GLU_DATAPATH_DELETE_FAILED,

  /* Domain error messages */
  CM_GLU_DOMAIN_ADD_FAILED,
  CM_GLU_DOMAIN_DELETE_FAILED,
  CM_GLU_DOMAIN_NOT_FOUND,
  CM_GLU_DOMAIN_SUBJECT_NAME_NULL,
  CM_GLU_DOMAIN_NUMOFTABLES_NULL,
  CM_GLU_DOMAIN_NUMOFTABLES_EXCEEDED,
  
  /* Switch error messages */
  CM_GLU_SWITCH_NAME_NULL,
  CM_GLU_SWITCH_ADD_FAILED,
  CM_GLU_SWITCH_DOESNOT_EXIST,
  CM_GLU_NO_MATCHING_RECORD,
  CM_GLU_SWITCH_DELETE_FAILED,
  CM_GLU_SWITCH_UPDATE_FAILED,
  
  CM_GLU_SWITCH_FQDN_NULL,
  CM_GLU_SWITCH_NAME_EXCEEDED,
  CM_GLU_SWITCH_BADDR_IP_NULL,

  /* Group error messages */
  CM_GLU_GROUP_DATAPATH_DOESNOT_EXIST,
  CM_GLU_GROUP_ADD_FAILED,
  CM_GLU_GROUP_EDIT_FAILED,
  CM_GLU_GROUP_DOESNOT_EXIST,
  CM_GLU_GROUP_ADD_TO_SWITCH_FAILED, 
  CM_GLU_GROUP_TYPE_INVALID,
  CM_GLU_GROUP_WEIGHT_REQUIRED,
  CM_GLU_GROUP_WATCH_PORT_OR_GROUP_REQUIRED,
  CM_GLU_GROUP_BUCKET_LIMIT_EXCEEDED,

  /* Port error messages */  
  CM_GLU_PORT_NAME_NULL,
  CM_GLU_PORT_ID_NULL,
  CM_GLU_PORT_ID_INVALID,
  CM_GLU_PORT_ADD_FAILED,
  CM_GLU_PORT_DELETE_FAILED,
  CM_GLU_NO_MATCHING_PORT_RECORD,

  /* Group description */
  CM_GLU_GROUPDESC_TYPE_INVALID,

  /* Flowmod error messages */
  CM_GLU_STATIC_FLOW_ADD_FAILED,
  CM_GLU_FLOW_ADD_FAILED,
  CM_GLU_FLOW_DOESNOT_EXIST,
  CM_GLU_FLOW_ADD_TO_SWITCH_FAILED,
  CM_GLU_FLOW_COOKIE_AND_MASK_MISSED,
  CM_GLU_FLOW_PRIORITY_MISSED,
  CM_GLU_FLOW_INVALID_MISSENTRY,
  CM_GLU_FLOW_INVALID_GOTOTABLE,
  	

  /* Bucket error messages*/
  CM_GLU_BUCKET_ADD_FAILED,
  CM_GLU_BUCKET_UPDATE_FAILED,
  CM_GLU_BUCKET_DOESNOT_EXIST,
  
  /* Action error messages */
  CM_GLU_ACTION_ADD_FAILED,
  CM_GLU_ACTION_DOESNOT_EXIST,
  CM_GLU_ACTION_INVALID,
  CM_GLU_PORT_OR_MAXLEN_NOT_CONFIGURED,
  CM_GLU_TTL_NOT_CONFIGURED,
  CM_GLU_ETHER_TYPE_NOT_CONFIGURED,
  CM_GLU_QUEUE_ID_NOT_CONFIGURED,
  CM_GLU_GROUP_ID_NOT_CONFIGURED,
 
  /* Meter error messages */
  CM_GLU_METER_DATAPATH_DOESNOT_EXIST,
  CM_GLU_METER_ADD_FAILED,
  CM_GLU_METER_EDIT_FAILED,
  CM_GLU_METER_DOESNOT_EXIST,
  CM_GLU_METER_ADD_TO_SWITCH_FAILED, 
  CM_GLU_METER_TYPE_INVALID,
  CM_GLU_METER_RATE_REQUIRED,
  CM_GLU_METER_PREC_LEVEL_REQUIRED,
  
  /* Meter config */
  CM_GLU_METERCONFIG_TYPE_INVALID,

  /* Band error messages*/
  CM_GLU_BAND_ADD_FAILED,
  CM_GLU_BAND_UPDATE_FAILED,
  CM_GLU_BAND_DOESNOT_EXIST,
  
  /* Few common messages */  
  CM_GLU_SET_MAND_PARAM_FAILED,
  CM_GLU_SET_OPT_PARAM_FAILED,
  CM_GLU_TABLE_ID_NULL,
  CM_GLU_MEMORY_ALLOCATION_FAILED,
  CM_GLU_VALIDATE_OPT_PARAM_FAILED,

  /* Port Attribute Messages */
  CM_GLU_ATTRIBUTE_ADD_FAILED,
  CM_GLU_ATTRIBUTE_MOD_FAILED,
  CM_GLU_GET_FIRST_ATTRIBUTE_NAME_FAILED,
  CM_GLU_ATTRIBUTE_DEL_FAILED,
  CM_GLU_CONTROLLER_DOESNOT_EXIST,	
  CM_GLU_SLAVE_CANNOT_SET,	
  CM_GLU_SET_ASYNC_OPTS_PARMS_FAILED,
  CM_GLU_SET_ASYNC_CFG_FAILED,
  CM_GLU_GROUP_DATAPATH_GET_NAMESPACE_COUNT_FAIL,
  CM_GLU_GROUP_DATAPATH_GET_NAMESPACE_FLAG_FAIL,
  CM_GLU_GROUP_DATAPATH_NAMESPACE_ENABLED,

  /* CRM Error Macros */
  CM_GLU_TENANT_ADD_FAILED,
  CM_GLU_TENANT_DEL_FAILED,
  CM_GLU_TENANT_NAME_NULL,
  CM_GLU_TENANT_ID_INVALID,
  CM_GLU_TRACE_MODULE_REQUIRED,
  CM_GLU_VM_ADD_FAILED,
  CM_GLU_VM_DEL_FAILED,
  CM_GLU_VM_NAME_NULL,
  CM_GLU_VM_TYPE_NULL,
  CM_GLU_SWITCH_NULL,
  CM_GLU_VN_ADD_FAILED,
  CM_GLU_VN_MOD_FAILED,
  CM_GLU_VN_DEL_FAILED,
  CM_GLU_VN_NAME_NULL,
  CM_GLU_VN_NAME_ID_INVALID,
  CM_GLU_VN_TYPE_NULL,
  CM_GLU_VN_TYPE_INVALID,
  CM_GLU_VN_SEG_ID_NULL,
  CM_GLU_VN_VXLAN_SERV_PORT_NULL,
  CM_GLU_VN_VLAN_PARAMS_NOT_SET,
  CM_GLU_VN_VXLAN_PARAMS_NOT_SET,
  CM_GLU_VN_DESC_NULL,
  CM_GLU_VN_DESC_INVALID,
  CM_GLU_VN_COMP_NODE_NAME_NULL,
  CM_GLU_BRIDGE_NAME_NULL,
  CM_GLU_VN_COMP_NODE_ADD_FAILED,
  CM_GLU_VN_COMP_NODE_DEL_FAILED,
  CM_GLU_SUBNET_ADD_FAILED,
  CM_GLU_SUBNET_DEL_FAILED,
  CM_GLU_SUBNET_NAME_NULL,
  CM_GLU_SUBNET_NAME_ID_INVALID,
  CM_GLU_SUBNET_POOL_START_ID_NULL,
  CM_GLU_SUBNET_POOL_END_ID_NULL,
  CM_GLU_SUBNET_IP_NULL,
  CM_GLU_SUBNET_MASK_NULL,
  CM_GLU_SUBNET_GATEWAY_IP_NULL,
  CM_GLU_SUBNET_IP_VERSION_NULL,
  CM_GLU_SUBNET_IP_VERSION_INVALID,
  CM_GLU_SUBNET_ENABLE_DHCP_NULL,
  CM_GLU_SUBNET_ENABLED_DHCP_INVALID,
  CM_GLU_SUBNET_DNS_SERVER_1_NULL,
  CM_GLU_SUBNET_DNS_SERVER_2_NULL,
  CM_GLU_SUBNET_DNS_SERVER_3_NULL,
  CM_GLU_SUBNET_DNS_SERVER_4_NULL,  
  CM_ATTRIBUTE_NAME_NULL,
  CM_ATTRIBUTE_VAL_NULL,
  CM_GLU_PORTTYPE_INVALID,
  CM_GLU_PORTNAME_INVALID,
  CM_GLU_CRM_PORT_ADD_FAILED,
  CM_GLU_PORTTYPE_NULL,
  CM_GLU_VM_SIDEPORT_MAC_NULL,
  CM_GLU_BRIDGENAME_INVALID,
  CM_GLU_VM_NAME_INVALID,
  CM_GLU_NW_TYPE_INVALID,
  CM_GLU_PORT_NAME_INVALID,
  CM_GLU_NWID_NULL,
  CM_GLU_SWITCH_NAME_INVALID,
  CM_GLU_VLAN_ID_NULL,
  CM_GLU_VXLAN_VNI_ID_NULL,
  CM_GLU_VXLAN_SERVICE_PORT_ID_NULL,
  CM_GLU_REMOTE_IP_NULL,
  CM_GLU_NW_PORT_VLAN_PARAMS_NOT_SET,
  CM_GLU_NW_PORT_VXLAN_PARAMS_NOT_SET,

  /*Transport Module Errors */
  CM_GLU_CNTLR_XPRT_INVALID_PROTOCOL_ID,

  /*Experimenter , bind , spd and sa stats error*/
  CM_GLU_IPSEC_DIRECTION_NULL,
  CM_GLU_SPD_POLICY_ID_NULL,
  CM_GLU_SA_SPI_ID_NULL,
  CM_GLU_SA_DEST_IP_ID_NULL,
  CM_GLU_SA_PROTOCOL_ID_NULL,

  /*NSRM Errors*/
  CM_GLU_SELECTION_RULE_ADD_FAILED,
  CM_GLU_SELECTION_RULE_DEL_FAILED,
  CM_GLU_SELECTION_RULE_MOD_FAILED,
  CM_GLU_SELECTION_RULE_NAME_NULL,
  CM_GLU_SELECTION_RULE_NAME_INVALID,

  CM_GLU_BYPASS_RULE_ADD_FAILED,
  CM_GLU_BYPASS_RULE_DEL_FAILED,
  CM_GLU_BYPASS_RULE_MOD_FAILED,
  CM_GLU_BYPASS_RULE_NAME_NULL,
  CM_GLU_BYPASS_RULE_NAME_INVALID,
 
  CM_GLU_NWSERVICE_ATTACH_FAILED,
  CM_GLU_PREVIOUS_NWSERVICE_NOT_SET,


  CM_GLU_NSCHAIN_SET_ADD_FAILED,
  CM_GLU_NSCHAIN_SET_DEL_FAILED,
  CM_GLU_NSCHAIN_SET_MOD_FAILED,
  CM_GLU_NSCHAIN_SET_NAME_NULL,
  CM_GLU_NSCHAIN_SET_NAME_INVALID,

  CM_GLU_NS_CHAIN_ADD_FAILED,
  CM_GLU_NS_CHAIN_DEL_FAILED,
  CM_GLU_NS_CHAIN_MOD_FAILED,
  CM_GLU_NS_CHAIN_NAME_NULL,
  CM_GLU_NS_CHAIN_NAME_INVALID,
  CM_GLU_NS_CHAIN_TYPE_NULL,
  CM_GLU_NS_CHAIN_TYPE_INVALID,
  CM_GLU_NS_CHAIN_TENANT_INVALID,


  CM_GLU_L2NW_ADD_FAILED,
  CM_GLU_L2NW_DEL_FAILED,
  CM_GLU_L2NW_MOD_FAILED,
  CM_GLU_L2NW_NAME_NULL,
  CM_GLU_L2NW_NAME_INVALID,
  CM_GLU_L2NW_MAPS_TO_OTHER_VN,

  CM_GLU_APPLIANCE_ADD_FAILED,
  CM_GLU_APPLIANCE_DEL_FAILED,
  CM_GLU_APPLIANCE_MOD_FAILED,
  CM_GLU_APPLIANCE_NAME_NULL,
  CM_GLU_APPLIANCE_NAME_INVALID,

  CM_GLU_SERVICE_INSTANCE_ADD_FAILED,
  CM_GLU_SERVICE_INSTANCE_DEL_FAILED,
  CM_GLU_SERVICE_INSTANCE_NAME_NULL,
    CM_GLU_MAX_ERR
  } UCMSecGluError_e;


