/* 
 *
 * Copyright  2012, 2013  Freescale Semiconductor
 *
 *
 * Licensed under the Apache License, version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
*/

/*
 *
 * File name: jeerror.h
 * Author: G Atmaram <B38856@freescale.com>
 * Date:   03/25/2013
 * Description: 
 * 
 */

#ifndef UCMJE_ERROR_H
#define UCMJE_ERROR_H

/* * * * * * * *  E R R O R S * * * * * * * * * * */
#define UCMJE_ERROR_STRING_LENGTH 256

#define ERROR_RESERVED "Error"
typedef enum
{
  /* Name and Value Pairs */
  UCMJE_DATA_ELEM_NAME_NULL = CM_JE_ERROR_BASE,
  UCMJE_DATA_ELEM_VALUE_NULL,

  /*Element Data Value type */
  UCMJE_DATA_ELEM_VALTYPE_INVALID_INT = (CM_JE_ERROR_BASE + 5),
  UCMJE_DATA_ELEM_VALTYPE_INVALID_UINT,
  UCMJE_DATA_ELEM_VALTYPE_INVALID_INT64,
  UCMJE_DATA_ELEM_VALTYPE_INVALID_UINT64,
  UCMJE_DATA_ELEM_VALTYPE_INVALID_STRING,
  UCMJE_DATA_ELEM_VALTYPE_INVALID_DATETIME,     /* 10 */
  UCMJE_DATA_ELEM_VALTYPE_INVALID_IPADDR,
  UCMJE_DATA_ELEM_VALTYPE_INVALID_IPV6ADDR,
  UCMJE_DATA_ELEM_VALTYPE_INVALID_BOOLEAN,
  UCMJE_DATA_ELEM_VALTYPE_INVALID,
  UCMJE_DATA_ELEM_VALTYPE_INVALID_XMLSTRING,  /*15*/

/*Element Data Value Semantic type */
  UCMJE_DATA_ATTRIB_INVALID_INT_RANGE = (CM_JE_ERROR_BASE + 20),
  UCMJE_DATA_ATTRIB_INVALID_INT_ENUM,   
  UCMJE_DATA_ATTRIB_INVALID_UINT_RANGE,
  UCMJE_DATA_ATTRIB_INVALID_UINT_ENUM,
  UCMJE_DATA_ATTRIB_INVALID_INT64_RANGE,
  UCMJE_DATA_ATTRIB_INVALID_INT64_ENUM,  /*25*/  
  UCMJE_DATA_ATTRIB_INVALID_UINT64_RANGE,
  UCMJE_DATA_ATTRIB_INVALID_UINT64_ENUM,
  UCMJE_DATA_ATTRIB_INVALID_STR_RANGE,
  UCMJE_DATA_ATTRIB_INVALID_STR_ENUM,
  UCMJE_DATA_ATTRIB_INVALID_IPADDR_RANGE,      /*30*/
  UCMJE_DATA_ATTRIB_INVALID_IPADDR_ENUM,
  UCMJE_DATA_ATTRIB_INVALID,

  /*je errors */
  /* Configuration Session */
  UCMJE_ERROR_CONFSESSION_ALREADY_EXISTS = (CM_JE_ERROR_BASE + 35),
  UCMJE_ERROR_CONFSESSION_START_FAILED,
  UCMJE_ERROR_UNKNOWN_CONFIGSESSION,
  UCMJE_ERROR_CONFIGSESSION_NULL,
  UCMJE_ERROR_UNKNOWN_SUB_COMMAND, /*39*/

  /* Transport Channel */
  UCMJE_ERROR_UNKNOWN_TRCHANNEL = (CM_JE_ERROR_BASE + 40),
  UCMJE_ERROR_UNKNOWN_TRCHANNEL_SUBCOMMAND,
  UCMJE_ERROR_MEMORY_ALLOCATION_FAILED,
  UCMJE_ERROR_VALIDATION_FAILED,
  UCMJE_ERROR_REFERRENCE_NOT_FOUND,
  UCMJE_ERROR_GET_INSTANCES_FAILED,
  UCMJE_ERROR_VERIFICATION_FAILED,
  UCMJE_ERROR_CONSOLIDATION_FAILED,

  /* Applicatin Callbacks */
  UCMJE_ERROR_APPCBK_NULL = (CM_JE_ERROR_BASE + 50),
  UCMJE_ERROR_TECKCBK_NULL,
  UCMJE_ERROR_TESTCBK_FAILED,
  UCMJE_ERROR_INVALID_PAIR_BEGINENDCBKS,
  UCMJE_ERROR_BEGINCBK_NULL,
  UCMJE_ERROR_ADDCBK_NULL,      /* 55 */
  UCMJE_ERROR_MODCBK_NULL,
  UCMJE_ERROR_DELCBK_NULL,
  UCMJE_ERROR_ENDCBK_NULL,
  UCMJE_ERROR_BEGINCBK_FAILED,
  UCMJE_ERROR_ADDCBK_FAILED,    /* 60 */
  UCMJE_ERROR_MODCBK_FAILED,
  UCMJE_ERROR_DELCBK_FAILED,
  UCMJE_ERROR_ENDCBK_FAILED,
  UCMJE_ERROR_GETFIRSTCBK_NULL,
  UCMJE_ERROR_GETNEXTCBK_NULL,  /* 65 */
  UCMJE_ERROR_GETEXACT_NULL,
  UCMJE_ERROR_GETFIRSTCBK_FAILED,
  UCMJE_ERROR_GETNEXTCBK_FAILED,
  UCMJE_ERROR_GETEXACT_FAILED,

  UCMJE_ERROR_INVALID_APLGET_CMD,       /* 70 */
  UCMJE_ERROR_GET_REQUEST_RECCOUNT_ZERO,
  UCMJE_ERROR_SET_DEFAULT_VALUE_FAILED,
  UCMJE_ERROR_MANDATORY_PARAM_NOT_SET,
  UCMJE_ERROR_CANCEL_COMMAND_NOT_FOUND,
  
	UCMJE_ERROR_KEY_CANNOT_BE_CANCELED, /* 75 */
	UCMJE_ERROR_MANDATORY_PARAM_CANNOT_BE_SET_TO_DEFAULT, /* 76 */

  /* Config version */
  UCMJE_ERROR_GET_NEWCONFIGVERSION_FAILED = (CM_JE_ERROR_BASE + 80),
  UCMJE_ERROR_ADDCMD_TO_CONFIGVERSION_FAILED,
  UCMJE_ERROR_CONFIG_CACHE,

  /* Audit Log */
  UCMJE_ERROR_GENERATE_AUDITLOG_FAILED,

  /* Notification */
  UCMJE_ERROR_NOTIFICATION_CONFIGUPDATE_FAILED,

  /* Data Model Instances */
  UCMJE_ERROR_ADD_INSTANCE_MAP_ENTRY_FAILED = (CM_JE_ERROR_BASE + 90),
  UCMJE_ERROR_GET_NEW_INSTANCEID_FAILED,
  UCMJE_ERROR_SET_NEW_INSTANCEID_FAILED,
  UCMJE_ERROR_GET_INSTANCES_LIST_FAILED,
  UCMJE_ERROR_DELETE_INSTANCE_FAILED,
  UCMJE_ERROR_DELETE_INODE_FAILED,
  UCMJE_ERROR_CREATE_NVPAIR_FROM_INSTANCE_ENTRY_FAILED,
  UCMJE_ERROR_ONE_OF_THE_PATH_KEYS_IS_NULL,

  /* Data Model */
  UCMJE_ERROR_DMPATH_NULL = (CM_JE_ERROR_BASE + 100),
  UCMJE_ERROR_DMPATH_INVALID,
  UCMJE_ERROR_REMOVE_DMPATH_KEYS,
  UCMJE_ERROR_GETNODE_BYDMPATH,
  UCMJE_ERROR_GETCHILD_BYNAME,
  UCMJE_ERROR_DMGETCHILD_BYID,
  UCMJE_ERROR_DMGET_KEYS_FROM_NAMEPATH_FAILED,
  UCMJE_ERROR_CREATE_NAMEPATH_FROM_DMNODE_FAILED,
  UCMJE_ERROR_CREATE_INSTANCEPATH_FROM_REFERRENCE_FAILED,
  UCMJE_ERROR_PERMISSION_DENIED,

  /* Data Model API erro */
  UCMJE_DMERROR_GET_DM_NODE_INFO_FAILED = (CM_JE_ERROR_BASE + 110),
  UCMJE_DMERROR_GET_DM_NODE_AND_CHILD_INFO_FAILED,
  UCMJE_DMERROR_GET_DM_KEY_CHILD_INFO_FAILED,
  UCMJE_DMERROR_GET_DM_FIRST_NODE_INFO_FAILED,
  UCMJE_DMERROR_GET_DM_NEXT_NODE_INFO_FAILED,
  UCMJE_DMERROR_GET_DM_KEYS_ARRAY_FAILED,       /* 115 */
  UCMJE_DMERROR_GET_DM_CHILD_NODE_INFO_FAILED,
  UCMJE_DMERROR_GET_DM_CHILD_NODE_COUNT_FAILED,
  UCMJE_DMERROR_GET_SAVE_FILE_NAME_FAILED,
  UCMJE_DMERROR_GET_SAVE_DIRECTORY_NAME_FAILED,
  UCMJE_DMERROR_IS_DM_CHILD_NODE_FAILED, /* 120 */
  UCMJE_DMERROR_UNKNOWN_DM_COMMAND,
  UCMJE_DMERROR_KEY_MANDATORY_NOTMATCHING,
  UCMJE_DMERROR_MANDATORY_GROUPED_SCALAR,


  UCMJE_DMERROR_GET_NEW_DM_INSTANCE_ID_FAILED=(CM_JE_ERROR_BASE + 130) , 
  UCMJE_DMERROR_ADD_DM_INSTANCE_ENTRY_FAILED,
  UCMJE_DMERROR_GET_DM_INSTANCE_MAPLIST_BY_NAMEPATH_FAILED,
  UCMJE_DMERROR_DEL_DM_INSTANCE_ENTRY_FAILED, 
  UCMJE_DMERROR_IS_DM_INSTANCE_USING_NAMEPATH_AND_KEY_FAILED,
  UCMJE_DMERROR_IS_DM_INSTANCE_USING_NAMEPATH_AND_KEYARRAY_FAILED,
  UCMJE_DMERROR_MAX_INSTANCES_REACHED,

	/* Roles */
  UCMJE_DMERROR_GET_DM_NODE_ROLE_ATTRIBS_FAILED= (CM_JE_ERROR_BASE + 140),
  UCMJE_DMERROR_GET_DM_NODE_ROLE_ATTRIBS_BY_ROLE_FAILED,
  UCMJE_DMERROR_SET_DM_NODE_ROLE_ATTRIBS_BY_ROLE_FAILED,
  UCMJE_DMERROR_DEL_DM_NODE_ROLE_ATTRIBS_BY_ROLE_FAILED,
  UCMJE_DMERROR_GET_DM_INSTANCE_ROLE_ATTRIBS_FAILED,
  UCMJE_DMERROR_SET_DM_INSTANCE_ROLE_ATTRIBS_FAILED,/*145*/
  UCMJE_DMERROR_GET_DM_INSTANCE_ROLE_ATTRIBS_BY_ROLE_FAILED,
  UCMJE_DMERROR_SET_DM_INSTANCE_ROLE_ATTRIBS_BY_ROLE_FAILED,       
  UCMJE_DMERROR_DEL_DM_INSTANCE_ROLE_ATTRIBS_BY_ROLE_FAILED,

  /* Ldsv */
  UCMJE_ERROR_SEND_TO_LDSV_FAILED = (CM_JE_ERROR_BASE + 150),
  UCMJE_ERROR_UNKNOWN_LDSV_SUB_COMMAND,
  UCMJE_ERROR_CREATE_TRANSCHANNEL_WTH_LDSV,
  UCMJE_ERROR_SAVE_CONFIG_IS_ALREADY_UPDATED,
  UCMJE_ERROR_SAVE_IS_IN_PROGRESS,
  UCMJE_ERROR_SAVE_CONFIG_FAILED,
  UCMJE_ERROR_LOAD_IS_IN_PROGRESS,
  UCMJE_ERROR_LOAD_CONFIG_FAILED,

	/*Authentication*/
  UCMJE_ERROR_USER_AUTHENTICATION_FAILED,

  UCMJE_ERROR_MAX_ERROR
} cm_je_error_e;

#define UCMJE_SUCCESS_STRING_LENGTH 256
typedef enum
{
  /* Name and Value Pairs */
  UCMJE_MAX_CONSOLIDATED_VERSION_REACHED = CM_JE_SUCCESS_BASE,
  UCMJE_WARNING_VERSION_HISTORY_LIMIT,
  UCMJE_SUCCESS_MAX_SUCCESSCODE
} cm_je_success_e;
#endif /* UCMJE_ERROR_H */
