/**SD_ROUTER_TTP: Following macros for SD_ROUTER Table type patterns.
    SD_ROUTER Table type patterns supports unicast,multicast and ipsec
    table types
 **/
/* SD_ROUTER unicast ,multicast &ipsec tables count*/ 
#define CNTLR_SD_ROUTER_TTP_TABLES_CNT 18

/**Following  8 tables for unicast table type patters **/
/*Table id0:In Port Classification Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID0_NAME "InPortClassificationTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID0_COLUMNS 1
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID0_ROWS    1024

/*Table id1:Etherenet Filtering Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID1_NAME "EtherenetFilteringTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID1_COLUMNS 2
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID1_ROWS    4096


/*Table id2:Ethernet Classification Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID2_NAME "EthernetClassificationTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID2_COLUMNS 1
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID2_ROWS    10


/*Table id3:ARP Inbound Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID3_NAME "ARPInboundTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID3_COLUMNS 4
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID3_ROWS    4000

/*Table id4:Ipv4 classification Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID4_NAME "Ipv4ClassificationTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID4_COLUMNS 2
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID4_ROWS    10


/*Table id5:IPV4 Policy Based Routing Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID5_NAME "IPV4PolicyBasedRoutingTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID5_COLUMNS 7
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID5_ROWS    4096


/*Table id6:IPv4 Routing Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID6_NAME "IPV4RoutingTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID6_COLUMNS 5
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID6_ROWS    (16*1024)

/*Table id7:ARP Resolution Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID7_NAME "ARPResolutionTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID7_COLUMNS 1
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID7_ROWS    1024


/*Table id8:IPv4MulticastGroupTable */
#define CNTLR_SD_ROUTER_TTP_MULTICAST_TABLE_ID8_NAME "IPV4MulticastGroupTable"
#define CNTLR_SD_ROUTER_TTP_MULTICAST_TABLE_ID8_COLUMNS 2
#define CNTLR_SD_ROUTER_TTP_MULTICAST_TABLE_ID8_ROWS    1024

/*Table id9:IPV4MFCTable */
#define CNTLR_SD_ROUTER_TTP_MULTICAST_TABLE_ID9_NAME "IPV4MFCTable"
#define CNTLR_SD_ROUTER_TTP_MULTICAST_TABLE_ID9_COLUMNS 4
#define CNTLR_SD_ROUTER_TTP_MULTICAST_TABLE_ID9_ROWS    1024

/*Table id11:IPSec Self IPV4 Classification Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID11_NAME "SelfIpv4ClassificationTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID11_COLUMNS 3
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID11_ROWS    1024


/*Table id12:IPSec Packet  Classification Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID12_NAME "IPSecPacketClassificationTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID12_COLUMNS 1
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID12_ROWS    1024



/*Table id13: Self  UDP classification table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID13_NAME "SelfUDPClassification Table"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID13_COLUMNS 5
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID13_ROWS    1024

/*Table id14: IPSecInboundSA Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID14_NAME "IPSecInboundSATable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID14_COLUMNS 4
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID14_ROWS    1024


/*Table id15: IPSecInbound Policy Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID15_NAME "IPSecInboundPolicyTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID15_COLUMNS 11
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID15_ROWS    1024

/*Table id16: IPSecOutbound Policy Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID16_NAME "IPSecOutboundPolicyTable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID16_COLUMNS 12
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID16_ROWS    1024

/*Table id17: IPSecOutbound SA Table */
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID17_NAME "IPSecOutboundSATable"
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID17_COLUMNS 12
#define CNTLR_SD_ROUTER_TTP_UNICAST_TABLE_ID17_ROWS    1024
